### ISSUE TITLE
Parsing does not raise error if there is a hole in the walls around the map

### ISSUE THREAD

**Issue by Alicia-bites** [Alicia-bites/cub3d#4]
You need cooling
Baby I'm not fooling
I'm gonna send ya
Back to schooliiiiiiiiiiiiing

bananananaNAnaNAA

**Comment by BarrierAntho** [comment]
fixed with ca783948071d635ce1f6daf926064acff941730a and fbbe391583a77fc62d1822e418da8dcf9d46aece

@Alicia-bites : TO BE TESTED with your own test file
